### PR TITLE
Use setuptools, store config in git configuration files, multi project support, and more

### PR DESCRIPTION
**Pull request by tremby**
With the extent of refactoring I wanted to do there was no chance of separate feature branches for everything here.
- Installation is now via setuptools. I have removed the update and install functions since in my opinion they didn't do anything useful.
- The binary and commit hook are now very short scripts which call functionality from the main module, `sprintly.py`. Setuptools installs the commit hook alongside the module, and it can be found there to be symlinked to.
- Installation and uninstallation of the git hook can now be done from any directory within the Git repository.
- There is now no ~/.sprintly/sprintly.config file. Instead all configuration is stored in the Git configuration files (whether global or repository-specific). Only the bare minimum is stored there: email and API key, product ID (which obviously is generally going to be set locally for each repository), plus some hook-specific ones I'll get to later.
- To easily get those config values I'm using the dulwich library. That makes it easy to save the config back, too.
- I took out the functionality to prompt for the Sprintly email and API key. This tool is aimed at developers. We know how to edit config files or use `git config`. So let's get rid of the unnecessary handholding. Since it is useful to give a choice of product IDs, on the other hand, I have left that functionality in so when running `sprintly` inside a Git repository the list is shown and the user can choose.
- When not in a Git repository it will show tickets for all products -- same when `--all` is given as an argument from inside a repository.
- We exit without a stack trace on KeyboardInterrupt, so we can control-C out when it's asking for the item number/product ID if we realize we've forgotten something, and not get an ugly error.
- I've added more consistent output colouring. Yellow for warnings, red for errors, green for success. I may not have been 100% consistent.
- Options are parsed in a separate method, which allows the main functionality to be called programatically without there having been any command line arguments (as will be the case in the commit hook).
- I've upgraded from optparse to argparse, which makes a few things easier.
- The only reference to subprocess is now calling an original git hook, if it exists. Everything else can be done in pure Python by referencing the sprintly.py module.
- On `--uninstall-hook` a `commit-msg.original` file is now moved back to `commit-msg`, otherwise it'd stop functioning.
- I've refactored `--install-hook` and `--uninstall-hook` to be much more robust. It will now move rather than obliterate a symlink to some other hook -- before it was assuming any symlink was our symlink. And the same for uninstall -- it won't delete a symlink if that symlink doesn't point to our hook.
- The commit hook now supports Sprintly's alternate ticket syntax (`ticket:44`, `issue:44` etc) as well as the normal `#44`.
- Instead of typing 0 for no reference to a ticket, just press enter. 0 was confusing.
- Multiple item numbers are allowed in the shortcut beginning-of-commit-message syntax if they are comma separated (but no whitespace except trailing after the last number).
- Configurable commit message template and item keyword. So instead of forcing `References #44` to the start of the commit message it can be at the start or end, have newlines etc around it, any other surrounding text. The item keyword can be changed from `#` too, which in my case is good because otherwise Github will pick up on it and get confused thinking it's talking about a pull request. So for instance the template string for the old-style commit message would be `References %(items)s %(messages)s`, my default is `%(message)s; references %(items)s` (much tidier at the end in my opinion) and for the projects I'm working on nowadays I am setting it to `%(message)s\n\nReferences %(items)s` with `sprintly.itemkeyword` set to `item:` so that I end up with things like

```
Commit message blah blah

References item:2, item:3
```
- There's a `--cache` argument which will pull the info from the cache rather than the internet. This is kinda buggy with the other new arguments...
- `--self` (default) grabs your own tickets but labels those belonging to other people (parents of your tickets), `--anyone` grabs everyone's tickets (including unassigned) and labels the assignee of each, `--unassigned` grabs just unassigned tickets (and labels those which _are_ assigned -- stories which are parents of unassigned).

Caveats:
- Running update on the old version will just not work, since that only downloaded one file and there are now more major files.
- The configuration obviously totally changed, so you will need to reconfigure username, API key and product ID. No big deal.
- `$PATH` isn't preserved for git hooks, so if your normal Python environment (and that with which the module was installed) is not in /usr/bin or /bin the module will not be found. In my case on my work machine I have Homebrew Python installed in /usr/local/Cellar/... and the only workaround I could find in a hurry was to move the original /usr/bin/python out of the way and put a symlink in pointing to Homebrew Python. I'd welcome a better solution.
- The `--cached` option isn't very good -- since different queries are now possible (for unassigned tickets, and for everyone's tickets, plus tickets from all products vs just the current one) only the last query is cached, so when using `--cached` with different options from when the cache was written the output will not make sense. Suggestions welcome.

If you decide to merge this in I'll suggest adding me as a maintainer and submitting it so it can be installed with easy_install.

If not, that's okay, I'll just keep working on my fork.

### CODE REVIEW

**Comment by markstos** [comment]
Looks excellent! I plan to try it as well.

**Comment by markstos** [comment]
It would be nice of the README explained how to use the "--all" flag (or multiple product Ids) in a pre-commit hook. I'm going to poke in the code some now and see if I can figure it out.

**Comment by markstos** [comment]
From my reading of the code, it appears neither `SprintlyCommitHook` nor the related `run` method support an options argument, so there's not currently a way to pass `--all` there. My preferred usage would be for this to be supported:

```
sprintly --install-hook -all
```

Supporting a list of product IDs would be nice as well. I have a Git repo which is used for two-of-three Sprint.ly projects that we have.

**Comment by tremby** [comment]
Hi, Mark. I no longer use Sprintly, so unless some team I'm working with in future is using it, I won't be maintaining my fork any longer. I'll add you as a contributor if you'd like.

**Comment by markstos** [comment]
@tremby Thanks for the prompt response. However, if you aren't using Sprintly anymore, I can just can use my own fork. 

From what I've seen so far I would recommend that your fork be merged here. 

If you don't mind sharing, did you switch to a competing project tracker?

**Comment by justinabrahms** [comment]
@markstos I haven't had a chance to finish code reviewing this, but I'm generally in favor of merging it. I'd like to see the $PATH issue resolved before merge, but haven't fully wrapped my head around what that is and if there's a reason we couldn't just us `/usr/bin/env` to bypass the python lookup.

Thanks so much for your work, @tremby. :)

**Comment by tremby** [comment]
@markstos certainly -- and I'll link to it if you like.

At my current longstanding contract position we've flitted between various bug trackers. Personally I think plain Github issues actually fits me best, but we've been through a bunch and have now settled back with Jira. But for how long...

@justinabrahms, my pleasure. Hope it's useful. Yeah, using `/usr/bin/env` may just well do the trick -- worth testing at least.

**Comment by markstos** [comment]
I just got an exception when trying to use the proposed code:

```
This git repository is not yet associated with a Sprint.ly product. You will now be prompted to choose one.
Enter Sprint.ly product id (XXXredactedXXX): Fatal error
ERROR:sprintly:Error occurred. Commit aborted.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sprintly_github-3.0.0-py2.7.egg/sprintly.py", line 752, in run
    self.process(commit_msg_path=sys.argv[1])
  File "/usr/local/lib/python2.7/dist-packages/sprintly_github-3.0.0-py2.7.egg/sprintly.py", line 785, in process
    self.display_sprintly_items()
  File "/usr/local/lib/python2.7/dist-packages/sprintly_github-3.0.0-py2.7.egg/sprintly.py", line 864, in display_sprintly_items
    sprintlyTool.run(sprintlyTool.getOptions([]))
  File "/usr/local/lib/python2.7/dist-packages/sprintly_github-3.0.0-py2.7.egg/sprintly.py", line 168, in run
    self.listSprintlyItems(options)
  File "/usr/local/lib/python2.7/dist-packages/sprintly_github-3.0.0-py2.7.egg/sprintly.py", line 338, in listSprintlyItems
    self.createSprintlyConfig()
  File "/usr/local/lib/python2.7/dist-packages/sprintly_github-3.0.0-py2.7.egg/sprintly.py", line 276, in createSprintlyConfig
    productId = getConfigItem(message)
  File "/usr/local/lib/python2.7/dist-packages/sprintly_github-3.0.0-py2.7.egg/sprintly.py", line 248, in getConfigItem
    item = raw_input('%s: ' % message)
EOFError: EOF when reading a line
```

**Comment by markstos** [comment]
I worked around the issue with the prompt failure above by manually editting my `.git/config` file in the project and adding a `[sprintly]` section with `product = 12345` (my product ID).   

Then I ran into another bug. I tried to enter "0" to proceed without a sprint.ly ticket number as the UI suggested. This just caused a loop, where the interface paused and then popped back up prompted me for a ticket number again.

**Comment by tremby** [comment]
> I just got an exception when trying to use the proposed code:

What did you do exactly when it was asking for a product ID? EOF when reading a line suggests you typed the number and then pressed ^D, which is unexpected. But if you're typing the number and pressing enter there must be a bug somewhere.

> Then I ran into another bug. I tried to enter "0" to proceed without a sprint.ly ticket number as the UI suggested.

Are you sure you're using my branch? This branch doesn't suggest to enter "0". sprintly.py line 876 provides the prompt "Enter item numbers separated by commas, or nothing to choose no item:" You're meant to just press enter to choose no item. Maybe that's not clear enough. See also the original post in this PR: "Instead of typing 0 for no reference to a ticket, just press enter. 0 was confusing."

> As best as I understand what happened, for some reason, both the "commit-msg" and "commit-msg.original" hook files were getting executed

Yes, both the installed hook and the original one are run. I don't recall if that was an original feature or if I added it. But I think the idea is that it's not a good thing to hack your own functionality into the Sprintly-provided hook, so we needed a way to also run your own hook. This should probably be a lot clearer, or even not allow it at all -- could refuse to install the hook if there already is one. As for it getting into a loop of calling both hooks over and over, that sounds like it's definitely a bug.

However, as explained above, I no longer use Sprintly and so won't be investigating or fixing this. I hope this branch is useful as a starting point all the same.

Fwiw, I'm currently on git 2.2.1. I'm not sure which version I developed against.

**Pull request closed without merging**
