### PR TITLE
Updated installation instructions to use Git rather than CURL.

### PR DESCRIPTION
**Pull request by F1LT3R**
I had trouble getting your CURL command install to work...

```shell
⮀curl -O https://raw.github.com/nextbigsoundinc/Sprintly-GitHub/master/sprintly
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
⮀ sudo python sprintly --install
Password: [password entered here]
python: can't open file 'sprintly': [Errno 2] No such file or directory
```

So I changed the commands to use a Git clone instead...

```markdown
	# download the latest version of the tool
	git clone https://github.com/nextbigsoundinc/Sprintly-GitHub.git

	# change to the repo directory
	cd Sprintly-GitHub

	# install
	sudo python sprintly --install
```

Perhaps this is an easier install for most users?

### CODE REVIEW

**Comment by F1LT3R** [comment]
:hourglass_flowing_sand:

**Comment by F1LT3R** [comment]
Wondering if this will still be looked at?

**Comment by wb** [comment]
@F1LT3R @mroderick the change looks good but I no longer have write access to this repository. We are looking into finding someone to take over this project, so stay tuned! https://twitter.com/samirrayani/status/562289304802959360

**Comment by nicholasserra** [comment]
Thanks! Can you modify this to show both install options? I just installed via curl with no problem. Would be nice to say install via curl or git.

**Comment by F1LT3R** [comment]
@nicholasserra https://github.com/F1LT3R/Sprintly-GitHub/commit/4717546fa7393c881a0f6869bc0112cc070ab79e

**Comment by nicholasserra** [comment]
Perfect. Looks like your fork needs synced with upstream, as I see a conflict. I could probably resolve it on merge if that's a hassle for you though. :)

**Comment by F1LT3R** [comment]
Looking...

**Comment by F1LT3R** [comment]
Let me know if that was what you were after @nicholasserra ?

**Comment by F1LT3R** [comment]
@nicholasserra, I also change what appeared to be a broken link, re: details on where to find your Sprint.ly API key.

Old link:
https://sprint.ly/account/profile/

New link:
http://help.sprint.ly/knowledgebase/articles/85725-where-do-i-find-my-api-key

**Comment by nicholasserra** [comment]
Looks great. Thanks again :)

**Comment by F1LT3R** [comment]
:+1:

**Pull request merged**
